name: "Build Debian Package"
author: "Kitsune Solar <kitsune.solar@gmail.com>"
description: "GitHub Action for build Debian source package."
branding:
  icon: "archive"
  color: "blue"
inputs:
  repo_src:
    description: "Repository (source)"
    required: true
  repo_dst:
    description: "Repository (destination)"
    required: true
  user:
    description: "User"
    required: true
  email:
    description: "E-mail"
    required: true
  token:
    description: "Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repo_src }}
    - ${{ inputs.repo_dst }}
    - ${{ inputs.user }}
    - ${{ inputs.email }}
    - ${{ inputs.token }}
